---
sudo: required
dist: trusty
services:
  - docker
language: python
python:
  - "2.7"
env:
  global:
    - ANSIBLE_ROLES_PATH: ~/roles
  matrix:
    - distro: ubuntu1604
      init: /lib/systemd/systemd
      run_opts: ""
    - distro: ubuntu1704
      init: /lib/systemd/systemd
      run_opts: ""
install:
  - pip install ansible==2.4.0
  - pip install ansible-lint==3.4.16
  - mkdir "${ANSIBLE_ROLES_PATH}"
  - printf "[defaults]\nhostfile=hosts\nansible_roles=${ANSIBLE_ROLES_PATH}" > ~/.ansible.cfg
script:
  - ./build
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
