---
- name: create sia group
  group:
    name: "{{ sia_group }}"
    state: present

- name: create sia user
  user:
    name: "{{ sia_user }}"
    group: "{{ sia_group }}"
    system: true

- name: install dependencies for downloading Sia archive
  apt:
    name: [ "unzip", "wget"]
    state: present
    update_cache: true  # TODO(mtlynch): Remove this.

- name: check for existing Sia installation
  stat:
    path: "{{ sia_dir }}"
  register: sia_dir_stat

- name: install Sia
  unarchive:
    src: "{{ sia_url }}"
    dest: "{{ sia_dir | dirname }}"
    remote_src: true
    owner: "{{ sia_user }}"
    group: "{{ sia_group }}"
  when: not sia_dir_stat.stat.exists

- name: set symlink to latest Sia version
  file:
    state: link
    src: "{{ sia_dir }}"
    dest: "{{ sia_symlink }}"
    owner: "{{ sia_user }}"
    group: "{{ sia_group }}"

- name: create sia data directory
  file:
    state: directory
    path: "{{ sia_data_dir }}"
    mode: 0755
    owner: "{{ sia_user }}"
    group: "{{ sia_group }}"

- name: check for consensus database
  stat:
    path: "{{ sia_data_dir }}/consensus/consensus.db"
    get_md5: false
    get_checksum: false
  register: consensus_file

- name: bootstrap consensus file
  import_tasks: bootstrap.yml
  when: sia_bootstrap_blockchain and not consensus_file.stat.exists

- name: change ownership to ansible user
  file:
    path: "{{ sia_data_dir }}"
    owner: "{{ sia_user }}"
    group: "{{ sia_user }}"
    recurse: true
    state: directory

- name: copy sia systemd service file
  template:
    src: sia.service.j2
    dest: /etc/systemd/system/sia.service
    mode: 0644
  notify:
    - reload systemd configs
    - restart sia service

- name: enable sia service
  systemd:
    name: sia
    enabled: true
    daemon_reload: true

- meta: flush_handlers

- name: verify sia service is running
  service:
    name: sia
    state: started

- name: wait until consensus is synced
  command: "{{ sia_siac_path }} consensus"
  register: consensus_result
  until: "consensus_result.stdout.find('Synced: Yes') >= 0"
  retries: "{{ 10 ** 6 }}"
  delay: 60
  when: sia_wait_for_sync
  changed_when: false

- name: create new seed
  import_tasks: create_seed.yml
  when: (sia_seed_path is not none) and
        (sia_seed_path | length > 0)

- name: load wallet from existing seed
  import_tasks: load_from_seed.yml
  when: (sia_wallet_password is not none) and
        (sia_wallet_password | length > 0) and
        (sia_seed is not none) and
        (sia_seed | length > 0)

- name: ensure wallet unlocked
  import_tasks: unlock_wallet.yml
  when: (sia_wallet_password is not none) and
        (sia_wallet_password | length > 0)
