---
- name: create sia group
  group:
    name: "{{ sia_group }}"
    state: present

- name: create sia user
  user:
    name: "{{ sia_user }}"
    group: "{{ sia_group }}"
    system: yes

- name: install dependencies for downloading Sia archive
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes # TODO(mtlynch): Remove this.
  with_items:
    - unzip
    - wget

- name: check for existing Sia installation
  stat:
    path: "{{ sia_dir }}"
  register: sia_dir_stat

- name: install Sia
  unarchive:
    src: "{{ sia_url }}"
    dest: "{{ sia_dir | dirname }}"
    remote_src: True
    owner: "{{ sia_user }}"
    group: "{{ sia_group }}"
  when: not sia_dir_stat.stat.exists

- name: set symlink to latest Sia version
  file:
    state: link
    src: "{{ sia_dir }}"
    dest: "{{ sia_symlink }}"
    owner: "{{ sia_user }}"
    group: "{{ sia_group }}"

- name: create sia data directory
  file:
    state: directory
    path: "{{ sia_data_dir }}"
    mode: 0755
    owner: "{{ sia_user }}"
    group: "{{ sia_group }}"

- name: check for consensus database
  stat:
    path: "{{ sia_data_dir }}/consensus/consensus.db"
  register: consensus_file

- name: bootstrap consensus file
  import_tasks: bootstrap.yml
  when: sia_bootstrap_blockchain and not consensus_file.stat.exists

- name: change ownership to ansible user
  file:
    path: "{{ sia_data_dir }}"
    owner: "{{ sia_user }}"
    group: "{{ sia_user }}"
    recurse: yes
    state: directory

- name: copy sia systemd service file
  template:
    src: sia.service.j2
    dest: /etc/systemd/system/sia.service
    mode: 0644
  notify:
    - reload systemd configs
    - restart sia service

- name: enable sia service
  service:
    name: sia
    enabled: yes
